version: "3.3"
services:

  datomic-free:
    image: datomic-free
    # container_name: dq-datomic-free
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-free
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base

  datomicdbfree:
    image: datomic-free
    # image: conj_datomicdb
    # container_name: dq-datomicdbfree
    # volumes:
    #   - "./.data/datomicdbfree:/opt/datomic-free/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4536:4336"
      - "4535:4335"
      - "4534:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/free-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-free


  datomicdbfreepeer:
    image: datomic-free
    # image: conj_datomicdb
    # container_name: conj-datomicdbpeer
    # volumes:
    #   - "./.data/datomicdb:/opt/datomic-pro/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    # command: ./bin/transactor ./config/dev-transactor.properties
    command: dockerize -wait http://create-dbs:8890/health -timeout 360s ./bin/run -m datomic.peer-server -h "0.0.0.0" -p 8998 -a myaccesskey,mysecret -d aligulac,datomic:free://datomicdbfree:4334/aligulac 
    # command: ./bin/run -m datomic.peer-server -h "0.0.0.0" -p 8998 -a myaccesskey,mysecret -d dayofdatomic,datomic:free://datomicdb:4334/dayofdatomic -d movies,datomic:dev://datomicdb:4334/movies -d tutorial,datomic:dev://datomicdb:4334/tutorial
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - datomicdbfree
      - create-dbs


  create-dbs:
    image: create-dbs
    # container_name: conj-create-dbs
    volumes:
      - ./create-dbs:/opt/code/app
    build:
      context: ./create-dbs
      dockerfile: ./Dockerfile
    # ports:
    #   - 35544:35543
      # - 8890:8890
    command: bash c init
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base
    links:
      - datomicdbfree
    healthcheck:
        test: ["CMD", "curl", "-f", "localhost:8890"]
        interval: 1s
        timeout: 0s
        retries: 100


  app-query:
    image: dq-app-query
    # container_name: dq-app-query
    volumes:
      - ./app-query:/opt/code/app
    build:
      context: ./app-query
      dockerfile: ./Dockerfile
    ports:
      - 37543:35543
      - 7988:7888
      - 8899:8890
    # command: tail -f /dev/null
    command: bash c start
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - datomicdbfree
      - postgresdb
    # depends_on:
    #   - base
  
  postgresdb:
    image: postgres:11.1
    # restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: aligulac
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aligulac

  adminer:
    image: adminer
    # restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
    ports:
      - 8787:8080


  load-aligulac-psql:
    image: dq-load-aligulac-psql
    # container_name: dq-load-aligulac-psql
    # volumes:
    #   - ./load-aligulac-psql:/opt/code/app
    build:
      context: ./load-aligulac-psql
      dockerfile: ./Dockerfile
    # ports:
    #   - 35543:35543
    #   - 7988:7888
    #   - 8890:8890
    # command: tail -f /dev/null
    command: bash c init
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - postgresdb
    # depends_on:
    #   - base


  load-aligulac-datomic:
    image: dq-load-aligulac-datomic
    # container_name: dq-load-aligulac-datomic
    volumes:
      - ./load-aligulac-datomic:/opt/code/app
    build:
      context: ./load-aligulac-datomic
      dockerfile: ./Dockerfile
    # ports:
    #   - 35543:35543
    #   - 7988:7888
    #   - 8890:8890
    command: tail -f /dev/null
    # command: bash c start
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - postgresdb
    # depends_on:
    #   - base


  dockerwheel:
    image: dq-dockerwheel
    # container_name: dq-dockerwheel
    volumes:
      - ./dockerwheel:/clj
    build:
      context: ./dockerwheel
      dockerfile: ./Dockerfile
    ports:
      - 3459:3449
      - 7979:7888
    # command: tail -f /dev/null
    command: lein figwheel
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - app-query
    # depends_on:
    #   - base