version: "3.3"
services:

  datomic-free:
    image: datomic-free
    container_name: dq-datomic-free
    # volumes:
    #   - ./.data/transactor:/opt/datomic-pro
    build:
      context: ./datomic-free
      dockerfile: ./Dockerfile
    # ports:
    #   - "4336:4336"
    #   - "4335:4335"
    #   - "4334:4334"
    #   - "9000:9000"
    # entrypoint: ./bin/transactor
    command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    # depends_on:
    #   - base

  datomicdbfree:
    image: datomic-free
    # image: conj_datomicdb
    container_name: dq-datomicdbfree
    # volumes:
    #   - "./.data/datomicdbfree:/opt/datomic-free/data"
    # build:
    #   context: ./datomic-pro
    #   dockerfile: ./Dockerfile
    ports:
      - "4436:4336"
      - "4435:4335"
      - "4434:4334"
      # - "9000:9000"
    # entrypoint: ./bin/transactor
    command: ./bin/transactor ./config/free-transactor.properties
    # command: config/dev-transactor.properties
    # command: tail -f /dev/null
    # command: bash c nrepl_clj
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    depends_on:
      - datomic-free


  app-query:
    image: dq-app-query
    container_name: dq-app-query
    volumes:
      - ./app-query:/opt/code/app
    build:
      context: ./app-query
      dockerfile: ./Dockerfile
    ports:
      - 35543:35543
      - 7988:7888
      - 8890:8890
    # command: tail -f /dev/null
    command: bash c start
    # environment:
    #   - DISPLAY=10.0.75.1:0.0
    stdin_open: true
    tty: true
    links:
      - datomicdbfree
    # depends_on:
    #   - base
  
  postgresdb:
    image: postgres:11.1
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aligulac

  adminer:
    image: adminer
    # restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
    ports:
      - 8787:8080