#!/bin/bash
# PGPASSWORD=postgres

init(){
    gunzip -c ./.data/aligulac.sql.gz | PGPASSWORD=postgres psql -h postgresdb -p 5432 -d aligulac -U aligulac 
    #  psql -h postgresdb -p 5432 -d aligulac -c  "CREATE ROLE aligulac"
}

"$@"
